name: portfolio-listener
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests
  - python-dotenv
  - pip
  - pandas
  - gspread
  - oauth2client
  - pip:
      # If you later need additional tools not in conda, put them here
      # - loguru
      # - pytest
      # - black
